version: '3.8'
services:
  web:
    container_name: django_postblog
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
#    entrypoint:
#      - "/usr/src/app/prestart.sh"

  db:
    env_file:
      - .env
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:latest
    ports:
    - 6379:6379

volumes:
  postgres_data: