# Generated by Django 3.1.3 on 2020-12-08 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_squashed_0003_auto_20201124_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(120, message='Длина текста меньше 150 символов')], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Заголовок должен состоять из букв и цифр', regex='[@#$%&*]+'), django.core.validators.MinLengthValidator(5, message='Длина заголовка меньше 5 символов')], verbose_name='Заглавие'),
        ),
    ]
