# Generated by Django 3.1.3 on 2020-12-10 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201209_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(help_text='Комментарий может содержать от 15 до 1000 символов', max_length=1000, validators=[django.core.validators.MinLengthValidator(15, message='Длина текста меньше 15 символов')], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, help_text='Не обязательное полне', max_length=254, null=True),
        ),
    ]
