# Generated by Django 3.1.3 on 2020-11-24 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201123_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(150, message='Длина текста меньше 150 символов')], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Заголовок должен состоять из букв и цифр', regex='\\W+'), django.core.validators.MinLengthValidator(5, message='Длина заголовка меньше 5 символов')], verbose_name='Заглавие'),
        ),
    ]
